name: cpDistiller
channels:
  - https://repo.anaconda.com/pkgs/r
  - pytorch
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - anndata
  - scanpy=1.9.3
  - h5py
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - ipykernel
  - jupyterlab
  - hnswlib
  - pip
  - pip:
      - conversions==0.0.2
      - deprecated==1.2.14
      - fbpca==1.0
      - geosketch==1.2
      - harmonypy==0.0.9
      - igraph==0.10.8
      - intervaltree==3.1.0
      - ipython-genutils==0.2.0
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.7.0
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-nbextensions-configurator==0.6.3
      - llvmlite==0.41.1
      - lxml==4.9.4
      - matplotlib==3.7.4
      - memory-profiler==0.61.0
      - nbclient==0.9.0
      - pandas==1.5.3
      - plottable==0.1.5
      - pydot==1.4.2
      - pytz-deprecation-shim==0.1.0.post0
      - rpy2==3.5.12
      - sortedcontainers==2.4.0
      - statsmodels==0.14.0
      - stdlib-list==0.10.0
      - tzlocal==4.3.1
      - wrapt==1.16.0
      - spektral==1.0.4
      - ipykernel
      - protobuf==3.20.2

